# Site settings
title: PYLER Tech Blog
description: 'Artificial Intelligence trends and concepts made easy.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pyler.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# logo: "/assets/img/branding/MVM-logo-full.svg"
logo: "/assets/img/branding/PYLER_logo.png"
# logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon: "/assets/img/branding/P_logo.png"
# logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file
logo-icon-SEO: "/assets/img/branding/P_logo.png"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "on"

logo-dark: "/assets/img/branding/PYLER_logo_dark.png"
logo-icon-dark: "/assets/img/branding/P_logo_dark.png"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: PYLER # add your name
author-pic: branding/P_logo.png
about-author: "파일러는 영상 분석 AI를 통해 콘텐츠의 맥락을 이해하고, 가장 어울리는 곳에 광고를 게재하여 브랜드 경험과 성과를 최적화하는 인공지능 마테크(Martech) 스타트업입니다."

# Contact links
email: ceo@pyler.tech # Add your Email address
phone: # Add your Phone number
website: https://www.rocketpunch.com/companies/pyler # Add your website
linkedin: company/주식회사-파일러 # Add your Linkedin handle
github: pylerAI # Add your Github handle
twitter: # Add your Twitter handle
bandcamp: # Add your Bandcamp username
stackoverflow: # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Disqus
discus_identifier: pylerai # Add your discus identifier
comments_curtain: yes # leave empty to show the disqus embed directly

# Tracker
analytics: G-QYKH11ZB11
# fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]